import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google"
import { cn } from "@/lib/utils"
import Navbar from "@/components/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

const links = [
  {
    title: "Home",
    path: "/",
  },
  {
    title: "Novidades",
    path: "/new",
  },
];

const linkButton = {
  title: "Comece Agora",
  path: "/login",
};

export default function SupportLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <section lang="en" className={cn(
      "min-h-screen bg-background font-sans antialiased",
      fontSans.variable
    )}>
      <Navbar links={links} linkButton={linkButton} />
      {children}
    </section>
  );
}
